#!/bin/sh
#Use this to add packages to your machine when running wu_setup_dev

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

#need to install node... to get npm... to install react-tools... to run jsx... to precompile react code into plain js
curl -sL https://rpm.nodesource.com/setup | bash -
yum install -y nodejs
npm install -g react-tools

# Install C++11
cd /etc/yum.repos.d
wget http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo 
yum --enablerepo=testing-1.1-devtools-6 --skip-broken install devtoolset-1.1-gcc devtoolset-1.1-gcc-c++
# Install Python 2.7.6
# install interpreter
cd /code/py
wget http://python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz --no-check-certificate
tar xf Python-2.7.6.tar.xz
cd Python-2.7.6
yum install zlib-devel
yum install openssl-devel
./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
make && make altinstall
# install pip (python module management)
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
python2.7 ez_setup.py
easy_install-2.7 pip
# install necessary modules
pip2.7 install requests
pip2.7 install -I progressbar==2.2
pip2.7 install simplemysql
pip2.7 install jenkinsapi
pip2.7 install redis
pip2.7 install dotmap
pip2.7 install numpy
pip2.7 install pymongo
pip2.7 install cluster
pip2.7 install tzlocal
pip2.7 install frozendict
pip2.7 install BeautifulSoup4
pip2.7 install simplemysql
pip2.7 install pycrypto
# delete unneeded python installation files
cd /code/py/
rm -rf /code/py/Python-2.7.6
rm -rf /code/py/Python-2.7.6.tar.xz*
